name: Sync LeetCode Solutions

on:
  schedule:
     - cron: "30 17 * * *" # daily at 11 PM IST

  workflow_dispatch: # allows manual run

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@v1.5
        with:
           github_token: ${{ secrets.LC_GITHUB_TOKEN }}
           leetcode-session: ${{ secrets.LEETCODE_SESSION }}
           leetcode-csrf-token: ${{ secrets.CSRF_TOKEN }}
           destination-folder: LeetCode

